# Generated by Django 5.0.6 on 2024-07-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(default='gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
