# Generated by Django 5.0.6 on 2024-07-05 19:18

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_organization_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='domain',
            field=models.CharField(help_text='Enter a valid domain name (e.g., example.com).', max_length=255, validators=[account.models.validate_domain]),
        ),
    ]
