# Generated by Django 5.0.6 on 2024-12-03 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_timeperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='account.timeperiod'),
        ),
    ]
