# Generated by Django 5.0.6 on 2024-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_assumption_modified_by_businessproblem_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assumption',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessproblem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
