# Generated by Django 5.0.6 on 2024-07-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_alter_assumption_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assumption',
            old_name='business_problem',
            new_name='business_problems',
        ),
        migrations.RenameField(
            model_name='assumption',
            old_name='strategy',
            new_name='strategies',
        ),
        migrations.RenameField(
            model_name='strategy',
            old_name='business_problem',
            new_name='business_problems',
        ),
    ]
