# Generated by Django 5.0.6 on 2024-07-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_rename_business_problem_assumption_business_problems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessproblem',
            old_name='team',
            new_name='teams',
        ),
    ]
