# Generated by Django 5.0.6 on 2024-10-06 22:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_alter_criterion_criterion_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planningeventstrategy',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='planningeventbusinessproblem',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='planningeventproject',
            name='scores',
        ),
        migrations.CreateModel(
            name='BusinessProblemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('criterion_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.criterionweight')),
                ('planning_event_business_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='strategy.planningeventbusinessproblem')),
                ('scoring_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('criterion_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.criterionweight')),
                ('planning_event_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='strategy.planningeventproject')),
                ('scoring_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('criterion_weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.criterionweight')),
                ('planning_event_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='strategy.planningeventstrategy')),
                ('scoring_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
