# Generated by Django 5.0.6 on 2024-10-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_remove_planningeventstrategy_scores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planningeventbusinessproblem',
            old_name='override_score',
            new_name='rank',
        ),
    ]
