# Generated by Django 5.0.6 on 2024-10-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_rename_override_score_planningeventbusinessproblem_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningeventbusinessproblem',
            name='final_score',
            field=models.FloatField(null=True),
        ),
    ]
