# Generated by Django 5.0.6 on 2024-11-24 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def add_owners(apps, schema_editor):
    Strategy = apps.get_model("strategy", "Strategy")
    db_alias = schema_editor.connection.alias
    Strategy.objects.using(db_alias).all().update(owner=F("created_by"))


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_strategy_owner_alter_planningevent_scoring_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_owners),
        migrations.AlterField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='strategy_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
