apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: strategyapp-ns
spec:
  selector:
    app: strategyapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
