apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: strategyapp-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: strategyapp
  template:
    metadata:
      labels:
        app: strategyapp
    spec:
      containers:
      - name: strategyapp
        image: jacobtomlinson21/strategyapp:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_HOST
          value: postgres-service
        - name: DB_PORT
          value: "5432"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: secret_key