apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: strategyapp-ns
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
