# Generated by Django 5.0.6 on 2024-07-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('strategy', '0002_strategy_is_chosen_alter_businessproblem_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='project', to='strategy.strategy'),
        ),
    ]
