# Generated by Django 5.0.6 on 2024-08-25 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_timeperiod'),
        ('project', '0002_alter_project_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.timeperiod'),
        ),
    ]
