# Generated by Django 5.0.6 on 2024-11-24 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def add_owners(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    db_alias = schema_editor.connection.alias
    Project.objects.using(db_alias).all().update(owner=F("created_by"))


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_owner_project_working_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(add_owners),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
